### ISSUE TITLE
Train Army Errors

### ISSUE THREAD

**Issue by BabyDragonn** [xbebenk/MBR_xbebenkMod#160]
Hi, after doing regular attacks i'm getting errors like these;
![train_error](https://github.com/xbebenk/MBR_xbebenkMod/assets/141275996/3afb9e51-f5d4-4366-814f-c231ff071556)
As result of these errors bot doesnt train next army, doesnt send cc request so that account misses attacks in next cycle.
Thanks in advance.

**Comment by nhumber** [comment]
[9:04:29 AM] Testing Train()
[9:04:30 AM] ====== TrainSystem =====
[9:04:32 AM] Click $aArmyTrainButton (Called from CheckIfArmyIsReady())
[9:04:37 AM] Cannot find Army Window...
[9:04:43 AM] Cannot find Army Window...
[9:04:48 AM] Cannot find Army Window...
[9:04:54 AM] Cannot find Army Window...
[9:05:00 AM] Cannot find Army Window...
[9:05:00 AM] [5] Check Opening ArmyWindow
[9:05:00 AM]  ====== CustomTrain ====== 
[9:05:05 AM] Cannot find Army Window...
[9:05:05 AM] getArmyTroops():
[9:05:06 AM] getArmySpells():
[9:05:12 AM] Cannot find Army Window...
[9:05:12 AM] -- TrainSiege --
[9:05:17 AM] Cannot find Army Window...
[9:05:20 AM] Testing Train DONE

alot of this cannot find army suddenly

**Comment by nhumber** [comment]
> [9:04:29 AM] Testing Train() [9:04:30 AM] ====== TrainSystem ===== [9:04:32 AM] Click $aArmyTrainButton (Called from CheckIfArmyIsReady()) [9:04:37 AM] Cannot find Army Window... [9:04:43 AM] Cannot find Army Window... [9:04:48 AM] Cannot find Army Window... [9:04:54 AM] Cannot find Army Window... [9:05:00 AM] Cannot find Army Window... [9:05:00 AM] [5] Check Opening ArmyWindow [9:05:00 AM] ====== CustomTrain ====== [9:05:05 AM] Cannot find Army Window... [9:05:05 AM] getArmyTroops(): [9:05:06 AM] getArmySpells(): [9:05:12 AM] Cannot find Army Window... [9:05:12 AM] -- TrainSiege -- [9:05:17 AM] Cannot find Army Window... [9:05:20 AM] Testing Train DONE
> 
> alot of this cannot find army suddenly

this is fixed with latest commits

**Comment by BabyDragonn** [comment]
![train_error1](https://github.com/xbebenk/MBR_xbebenkMod/assets/141275996/ce7cda60-2a92-4d15-ae95-06e4d21f8bb7)
Mine didnt change with latest commits

**Comment by xbebenk** [comment]
> ![train_error1](https://private-user-images.githubusercontent.com/141275996/300207032-ce7cda60-2a92-4d15-ae95-06e4d21f8bb7.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzOTkzMDAsIm5iZiI6MTcwNjM5OTAwMCwicGF0aCI6Ii8xNDEyNzU5OTYvMzAwMjA3MDMyLWNlN2NkYTYwLTJhOTItNGQxNS1hZTk1LTA2ZTRkMjFmOGJiNy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyN1QyMzQzMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NTlkMjEzOTUzZjYwN2Q1YzdmMTUyNTBlY2FhOGVhOWI0NjI0ZjZjMmFhYjc2MTM0YzUwODEwMGRkY2RkMjFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fShb5zT0XMuoY-SHrxuJ7igGc1X53UlfixJ-WHHIuR0) Mine didnt change with latest commits Bot mostly doing 1 attack and changes to next account, not even training army for the next attack. PS: Using "[d8f737a](https://github.com/xbebenk/MBR_xbebenkMod/tree/d8f737ada1719305f5f97127ef22df6e05a9b81c)" version until a fix implemented, its working great for me.

no, you not using latest commit
![image](https://github.com/xbebenk/MBR_xbebenkMod/assets/6594360/308e5b2f-87b8-4982-ad66-81aa4de50958)

**Comment by benhayes36** [comment]
xbebenk, I can confirm that the issue still exists with the current commit.  I have 8 accounts in 2 switch groups and all the accounts experience this issue.  The commit I'm using is:

Commit: 16a955dbe112cc7d5396511914fa77e221852534 [16a955d]

At the moment I've shutdown my bots until this is fixed or until I can determine a commit to go back to to resolve this.  It was working a few days back but each commit I've pulled hasn't resolved the issue.

Here is one of my logs from today using the latest commit:

https://pastes.io/3g4ferxjii

**Comment by BabyDragonn** [comment]
I'm %100 sure that i was using latest commit thats uploaded 9 hours ago in those screenshots and that error still there in latest version. I found an earlier version which doesnt have that bug and using it right now.

**Comment by benhayes36** [comment]
I believe somewhere around Commit: 0a88528875960076944e583512ac223922371def [0a88528] it was working.  I need to start taking notes on which commits I have been upgrading and what worked and not worked with each.

**Comment by BabyDragonn** [comment]
[d8f737a](https://github.com/xbebenk/MBR_xbebenkMod/tree/d8f737ada1719305f5f97127ef22df6e05a9b81c) is a little old one but working perfect.

**Comment by benhayes36** [comment]
Personally, I believe it is the latest commit or the one before that which is causing the issue.  I could be mistaken but I do remember it working before I pulled the commit yesterday and again today.

**Comment by benhayes36** [comment]
@xbebenk There are still issues with the train army.  The commit you did last night fixed part of the issues but there are still issues.  I'm seeing issues in my armies when using GiWiz that giants seem to be training but not wizards.  To make matters worse, the army size for the Giants is more than what is setup to train and the bot isn't going back to remove the overage of Giants.  Here is one of my logs from the latest commit.  I'll check the other accounts soon where I'm using Super Barbarians.

https://pastes.io/spyzniqob6
